; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.5
    yuriisalimov/NTC_Thermistor
    marian-craciunescu/ESP32Ping@^1.7
	jandrassy/TelnetStream@^1.3.0
; Flash configuration
board_upload.flash_size = 4MB
board_build.partitions = default.csv


; Serial Monitor options
monitor_speed = 115200

; Required flags to enable Serial output via the native USB-C port
build_unflags = 
    -D ARDUINO_USB_MODE
    -D ARDUINO_USB_CDC_ON_BOOT
build_flags = 
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
upload_protocol = espota
upload_port = 10.1.1.23
upload_flags = 
	--auth=YOUR_PASSWORD_HERE
	--port=1723
	--host_port=16161
	--host_ip=10.1.1.3

